### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by jakeret** [samconnolly/DELightcurveSimulation#1]
It seems that the example that is shipped with the package and the one in the readme are no longer working with the package API.

After I adapted the import statement to `from DELCgen import *` I get the following traceback:

```
 Traceback (most recent call last):
  File "/xxx/xxx/workspace/DELCgen/example.py", line 43, in <module>
    RedNoiseL,aliasTbin,RandomSeed)
  File "/xxx/xxx/workspace/DELCgen/DELCgen.py", line 1313, in Simulate_TK_Lightcurve
    if lightcurve.std_est == None:
AttributeError: 'tuple' object has no attribute 'std_est'
```

Similar exception when calling `delc_mod = Simulate_DE_Lightcurve(...)`. 

I'm also not able to call `Simulate_DE_Lightcurve`:

```
Traceback (most recent call last):
  File "/xxx/xxx/workspace/DELCgen/example2.py", line 39, in <module>
    delc = datalc.Simulate_DE_Lightcurve() # defaults to bending PL and mix of gamma and lognormal dist.
  File "/xxx/xxx/workspace/DELCgen/DELCgen.py", line 984, in Simulate_DE_Lightcurve
    self.pdfModel,self.pdfFit['x'], size = size, LClength=LClength)
  File "/xxx/xxx/workspace/DELCgen/DELCgen.py", line 1414, in Simulate_DE_Lightcurve
    if lightcurve:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by samconnolly** [comment]
Apologies for not seeing this sooner. The example was indeed broken, as I had updated some of the input parameters but didn't change the example. It should now work!

**Comment by jakeret** [comment]
Cool, thanks
